### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by FFY00** [Evrytania/LTE-Cell-Scanner#22]
```
anubis@FFY00:~/git/LTE-Cell-Scanner/build$ LTE-Tracker -g 30 -p 47
Warning: Frequency not specified. Make sure you are working on captured file.
OpenCL LTE Tracker (release) beginning. 1.0 to 1.1.0: OpenCL/TDD/HACKRF/bladeRF/ext-LNB added by Jiao Xianjun(putaoshu@gmail.com)
  PPM: 47
  correction: 1
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
RTLSDR device FOUND!
Calibrating local oscillator.
Use file begin with 6.95329e-316MHz actual 2.37663e-318MHz 1.91631e-316MHz
    Search frequency: 6.95329e-316 to 6.95329e-316 MHz
with freq correction: 0 kHz
Segmentation fault (core dumped)

```

**Comment by TeddJohnson** [comment]
I see that you closed this, was there a fix?

**Comment by Matyeszka** [comment]
diff --git a/include/dsp.h b/include/dsp.h
index fcba157..3c68a67 100644
--- a/include/dsp.h
+++ b/include/dsp.h
@@ -44,8 +44,8 @@ inline itpp::cvec fshift(const itpp::cvec &seq,const double f,const double fs) {
   itpp::cvec r(len);
   std::complex<double>coeff;
   for (uint32 t=0;t<len;t++) {
-    coeff.real()=cos(k*t);
-    coeff.imag()=sin(k*t);
+    coeff.real(cos(k*t));
+    coeff.imag(sin(k*t));
     //r(t)=seq(t)*exp(k*((double)t));
     r(t)=seq(t)*coeff;
   }
@@ -61,8 +61,8 @@ inline void fshift_inplace(itpp::cvec &seq,const double f,const double fs) {
   const uint32 len=length(seq);
   std::complex<double>coeff;
   for (uint32 t=0;t<len;t++) {
-    coeff.real()=cos(k*t);
-    coeff.imag()=sin(k*t);
+    coeff.real(cos(k*t));
+    coeff.imag(sin(k*t));
     //r(t)=seq(t)*exp(k*((double)t));
     seq(t)*=coeff;
   }
diff --git a/src/from_osmocom.cpp b/src/from_osmocom.cpp
index 339b171..751f8d1 100644
--- a/src/from_osmocom.cpp
+++ b/src/from_osmocom.cpp
@@ -120,7 +120,6 @@ double compute_fc_programmed(const double & fosc,const double & intended_flo)
        uint64_t intended_fvco, remainder;
        uint64_t z = 0;
        uint32_t x;
-       int flo;
        int three_phase_mixing = 0;
        oscp->r_idx = 0;
 
@@ -151,7 +150,7 @@ double compute_fc_programmed(const double & fosc,const double & intended_flo)
        x = (remainder * E4K_PLL_Y) / fosc;
        /* x(max) as result of this computation is 65536 */
 
-       flo = compute_flo(fosc, z, x, r);
+       auto flo = compute_flo(fosc, z, x, r);
 
        oscp->fosc = fosc;
        oscp->flo = flo;
diff --git a/src/producer_thread.cpp b/src/producer_thread.cpp
index 6c72618..a24ca84 100644
--- a/src/producer_thread.cpp
+++ b/src/producer_thread.cpp
@@ -124,9 +124,9 @@ void producer_thread(
           n_samples=t;
           break;
         }
-        sample_temp.real()=(sampbuf_sync.fifo.front()-127.0)/128.0;
+        sample_temp.real((sampbuf_sync.fifo.front()-127.0)/128.0);
         sampbuf_sync.fifo.pop_front();
-        sample_temp.imag()=(sampbuf_sync.fifo.front()-127.0)/128.0;
+        sample_temp.imag((sampbuf_sync.fifo.front()-127.0)/128.0);
         sampbuf_sync.fifo.pop_front();
         samples(t)=sample_temp;
         sample_time+=(FS_LTE/16)/(fs_programmed*k_factor);
diff --git a/src/tracker_thread.cpp b/src/tracker_thread.cpp
index c903685..d054341 100644
--- a/src/tracker_thread.cpp
+++ b/src/tracker_thread.cpp
@@ -163,10 +163,10 @@ void get_fd(
   const complex <double> bpo_coeff=complex<double>(cos(bulk_phase_offset),sin(bulk_phase_offset));
   for (uint8 t=1;t<=36;t++) {
     phase=-k*t;
-    coeff.real()=cos(phase);
-    coeff.imag()=sin(phase);
+    coeff.real(cos(phase));
+    coeff.imag(sin(phase));
     syms(35+t)*=bpo_coeff*coeff;
-    coeff.imag()=-coeff.imag();
+    coeff.imag(-coeff.imag());
     syms(36-t)*=bpo_coeff*coeff;
   }
   // At this point, we have the frequency domain data for this slot and

**Comment by Matyeszka** [comment]
`diff --git a/include/dsp.h b/include/dsp.h
index fcba157..3c68a67 100644
--- a/include/dsp.h
+++ b/include/dsp.h
@@ -44,8 +44,8 @@ inline itpp::cvec fshift(const itpp::cvec &seq,const double f,const double fs) {
   itpp::cvec r(len);
   std::complex<double>coeff;
   for (uint32 t=0;t<len;t++) {
-    coeff.real()=cos(k*t);
-    coeff.imag()=sin(k*t);
+    coeff.real(cos(k*t));
+    coeff.imag(sin(k*t));
     //r(t)=seq(t)*exp(k*((double)t));
     r(t)=seq(t)*coeff;
   }
@@ -61,8 +61,8 @@ inline void fshift_inplace(itpp::cvec &seq,const double f,const double fs) {
   const uint32 len=length(seq);
   std::complex<double>coeff;
   for (uint32 t=0;t<len;t++) {
-    coeff.real()=cos(k*t);
-    coeff.imag()=sin(k*t);
+    coeff.real(cos(k*t));
+    coeff.imag(sin(k*t));
     //r(t)=seq(t)*exp(k*((double)t));
     seq(t)*=coeff;
   }
diff --git a/src/from_osmocom.cpp b/src/from_osmocom.cpp
index 339b171..751f8d1 100644
--- a/src/from_osmocom.cpp
+++ b/src/from_osmocom.cpp
@@ -120,7 +120,6 @@ double compute_fc_programmed(const double & fosc,const double & intended_flo)
        uint64_t intended_fvco, remainder;
        uint64_t z = 0;
        uint32_t x;
-       int flo;
        int three_phase_mixing = 0;
        oscp->r_idx = 0;
 
@@ -151,7 +150,7 @@ double compute_fc_programmed(const double & fosc,const double & intended_flo)
        x = (remainder * E4K_PLL_Y) / fosc;
        /* x(max) as result of this computation is 65536 */
 
-       flo = compute_flo(fosc, z, x, r);
+       auto flo = compute_flo(fosc, z, x, r);
 
        oscp->fosc = fosc;
        oscp->flo = flo;
diff --git a/src/producer_thread.cpp b/src/producer_thread.cpp
index 6c72618..a24ca84 100644
--- a/src/producer_thread.cpp
+++ b/src/producer_thread.cpp
@@ -124,9 +124,9 @@ void producer_thread(
           n_samples=t;
           break;
         }
-        sample_temp.real()=(sampbuf_sync.fifo.front()-127.0)/128.0;
+        sample_temp.real((sampbuf_sync.fifo.front()-127.0)/128.0);
         sampbuf_sync.fifo.pop_front();
-        sample_temp.imag()=(sampbuf_sync.fifo.front()-127.0)/128.0;
+        sample_temp.imag((sampbuf_sync.fifo.front()-127.0)/128.0);
         sampbuf_sync.fifo.pop_front();
         samples(t)=sample_temp;
         sample_time+=(FS_LTE/16)/(fs_programmed*k_factor);
diff --git a/src/tracker_thread.cpp b/src/tracker_thread.cpp
index c903685..d054341 100644
--- a/src/tracker_thread.cpp
+++ b/src/tracker_thread.cpp
@@ -163,10 +163,10 @@ void get_fd(
   const complex <double> bpo_coeff=complex<double>(cos(bulk_phase_offset),sin(bulk_phase_offset));
   for (uint8 t=1;t<=36;t++) {
     phase=-k*t;
-    coeff.real()=cos(phase);
-    coeff.imag()=sin(phase);
+    coeff.real(cos(phase));
+    coeff.imag(sin(phase));
     syms(35+t)*=bpo_coeff*coeff;
-    coeff.imag()=-coeff.imag();
+    coeff.imag(-coeff.imag());
     syms(36-t)*=bpo_coeff*coeff;
   }
   // At this point, we have the frequency domain data for this slot and
`

**Comment by Matyeszka** [comment]
[LTE-Cell-Scanner-fixes.diff.txt](https://github.com/Evrytania/LTE-Cell-Scanner/files/5015577/LTE-Cell-Scanner-fixes.diff.txt)
