### ISSUE TITLE
LAPACK library is needed to use inv() function

### ISSUE THREAD

**Issue by jjbaek35** [Evrytania/LTE-Cell-Scanner#24]
Hi all,

Could you find it out what's the problem?

root@deli:~/lte/LTE-Cell-Scanner/build# CellSearch --freq-start 1800e6 --freq-end 1900e6
LTE CellSearch v1.0.0 (release) beginning
  Search frequency range: 1800-1900 MHz
  PPM: 120
  correction: 1
Found Elonics E4000 tuner
Examining center frequency 1800 MHz ...
*** Error in /root/lte/LTE-Cell-Scanner/build/itpp-4.3.1/itpp/base/algebra/inv.cpp on line 95:
LAPACK library is needed to use inv() function
Aborted

**Comment by jjbaek35** [comment]
I solved it by re-install IT++ version 4.3.1.
Thanks.

**Comment by jjbaek35** [comment]
I solved it by re-install IT++ version 4.3.1.
Thanks.

**Comment by maoke123** [comment]
I have the same problem, but the error remains even reinstalling 4.3.1. I guess there is a maybe  problem with my compiling. my syntax is 
   g++ example.cpp -o example  -L/opt/intel/mkl/lib/intel64/libmkl_lapack95_lp64  -litpp
