### ISSUE TITLE
Cmake are okay success, but "make" is failed make[2]: *** [src/CMakeFiles/LTE_MISC.dir/searcher.cpp.o] Error 4

### ISSUE THREAD

**Issue by arifkyi** [Evrytania/LTE-Cell-Scanner#30]
Hello  LTE Scanner team,

I have an issue below when installing LTE Scanner,

it said: make[2]: *** [src/CMakeFiles/LTE_MISC.dir/searcher.cpp.o] Error 4,

looking forward for the resolution.

sudo make
[  5%] Building CXX object src/CMakeFiles/LTE_MISC.dir/capbuf.cpp.o
[ 11%] Building CXX object src/CMakeFiles/LTE_MISC.dir/constants.cpp.o
[ 16%] Building CXX object src/CMakeFiles/LTE_MISC.dir/itpp_ext.cpp.o
[ 22%] Building CXX object src/CMakeFiles/LTE_MISC.dir/macros.cpp.o
[ 27%] Building CXX object src/CMakeFiles/LTE_MISC.dir/searcher.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/CMakeFiles/LTE_MISC.dir/build.make:158: recipe for target 'src/CMakeFiles/LTE_MISC.dir/searcher.cpp.o' failed
make[2]: *** [src/CMakeFiles/LTE_MISC.dir/searcher.cpp.o] Error 4
CMakeFiles/Makefile2:121: recipe for target 'src/CMakeFiles/LTE_MISC.dir/all' failed
make[1]: *** [src/CMakeFiles/LTE_MISC.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by velichkov** [comment]
Hi @arifkyi,

> [ 27%] Building CXX object src/CMakeFiles/LTE_MISC.dir/searcher.cpp.o
> c++: internal compiler error: Killed (program cc1plus)

Try adding some more RAM or a swap. See https://github.com/ptrkrysik/gr-gsm/issues/236#issuecomment-264711773 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61860

I just compiled it successfully on Ubuntu 16.04.

**Comment by arifkyi** [comment]
Hello Vasil,

wow, meet you again here, before we had discussion in grgsm issue as you also contributor there.


Good news: i have success full installation, 
what the fix:  
0. i install this :  sudo apt-get install cmake libncurses5-dev liblapack-dev libblas-dev libboost-thread-dev libboost-system-dev libitpp-dev librtlsdr-dev libfftw3-dev

 1. i follow the step original steps but i make a change in  here CmakeLists.txt  from “SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -ggdb -Wall") “  to be “ SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++03 -ggdb -Wall”)"

2. before i had issue with ITTP although in step 0 already ITTU shown, i follow this step:  https://stackoverflow.com/questions/41077559/quick-and-hassle-free-installation-usage-of-it-library-on-linux-windows

3. install :
install Find RTL SDR, source: 
https://drwxr.org/2016/10/installing-rtl-sdr-rtl2832u-driver/
sudo apt-get install libusb-1.0-0-dev
Download and install the RTL2832U from vendor site:
git clone git://git.osmocom.org/rtl-sdr.git
cd rtl-sdr/
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo ldconfig
sudo cp ../rtl-sdr.rules /etc/udev/rules.d/
4. Voila, i can enjoy the LTE search,   yiippppyy.


Anyway, a question is there any similar gr-gsm_livemon or capture (  NO  NEED DECODE)  for 3G and 4G/LTE  ?

thank you very much for your expert support

br,
rifky

**Comment by velichkov** [comment]
Hi @arifkyi,

> 2. before i had issue with ITTP although in step 0 already ITTU shown, 

You need to patch `cmake/Modules/FindITPP.cmake` in order to find the version from `libitpp-dev` package. See https://github.com/Evrytania/LTE-Cell-Scanner/issues/28#issuecomment-450546148

> Anyway, a question is there any similar gr-gsm_livemon or capture ( NO NEED DECODE) for 3G and 4G/LTE ?

AFAIK a FOSS equivalent of `grgsm_livemon` for 3G/4G still does not exists. Have a look at https://github.com/JiaoXianjun/LTE-Cell-Scanner fork, it contains support for more SDR devices and several other enhancements.

**Comment by arifkyi** [comment]
Hello Vasil,

Thank you very much.
