### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by amrabbas** [Evrytania/LTE-Cell-Scanner#8]
When I try the command: CellSearch --freq-start 791000000
I get:

LTE CellSearch v1.0.0 (release) beginning
   Search frequency: 791 MHz
   PPM: 120
   correction: 1
Found Rafael Micro R820 tuner
Examining center frequency 791 MHz ...

but then it stops here and gets stuck without giving any output. What could be the reason for this?

Thanks for your help

**Comment by f4gkr** [comment]
The process can be very long depending on your computer performances...
re-run with verbose option (-v) and check the search evolution

sylvain

2014-07-15 16:28 GMT+02:00 amrabbas notifications@github.com:

**Comment by JiaoXianjun** [comment]
if you have opencl driver installed, you may try opencl lte cell scanner,.which is faster.

just google "opencl lte cell scanner"

Sylvain AZARIAN notifications@github.com wrote:

The process can be very long depending on your computer performances...
re-run with verbose option (-v) and check the search evolution

sylvain

2014-07-15 16:28 GMT+02:00 amrabbas notifications@github.com:

> When I try the command: CellSearch --freq-start 791000000
> I get:
> 
> LTE CellSearch v1.0.0 (release) beginning
> Search frequency: 791 MHz
> PPM: 120
> correction: 1
> Found Rafael Micro R820 tuner
> Examining center frequency 791 MHz ...
> 
> but then it stops here and gets stuck without giving any output. What
> could be the reason for this?
> 
> Thanks for your help
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Evrytania/LTE-Cell-Scanner/issues/8.

---

**Comment by amrabbas** [comment]
Thanks for the help. I just needed to wait for it to finish.

**Comment by amrabbas** [comment]
Hello Again,

I have another question. I used to run the LTE Cell Scanner on a Raspberry Pi and it took around one hour to scan 1 frequency. 

I plan to get NVIDIA JETSON TK1 or a similar device and my question is have you used the scanner with a similar device and if yes, could you tell me how much does is take to scan a frequency on such a device?

Thanks in advance

**Comment by JiaoXianjun** [comment]
I have an opencl version, which is much faster, and tested in intel cpu and nvidia desktop gpu.  You may search "opencl lte cell scanner" to see video introduction.

For your board, it may need little code tuning. Any problem, I will be glad to help.

amrabbas notifications@github.com编写：

Hello Again,

I have another question. I used to run the LTE Cell Scanner on a Raspberry Pi and it took around one hour to scan 1 frequency.

I plan to get NVIDIA JETSON TK1 or a similar device and my question is have you used the scanner with a similar device and if yes, could you tell me how much does is take to scan a frequency on such a device?

Thanks in advance

---

**Comment by JiaoXianjun** [comment]
Or search "Jiao XIanjun" in github

XianJun Jiao putaoshu@msn.com编写：

I have an opencl version, which is much faster, and tested in intel cpu and nvidia desktop gpu.  You may search "opencl lte cell scanner" to see video introduction.

For your board, it may need little code tuning. Any problem, I will be glad to help.

amrabbas notifications@github.com编写：

Hello Again,

I have another question. I used to run the LTE Cell Scanner on a Raspberry Pi and it took around one hour to scan 1 frequency.

I plan to get NVIDIA JETSON TK1 or a similar device and my question is have you used the scanner with a similar device and if yes, could you tell me how much does is take to scan a frequency on such a device?

Thanks in advance

---

**Comment by amrabbas** [comment]
Ok, I'll look for it but how long does it normaly take according to your previous runs?

**Comment by JiaoXianjun** [comment]
around 2s for one frequency point (search -50kHz to +50kHz around the point, because frequency step is 0.1MHz) in my T410 (Intel® Core™ i5 CPU M 520 @ 2.40GHz × 4)

**Comment by amrabbas** [comment]
Thanks for your help. I'll try it.

**Comment by amrabbas** [comment]
Hi JiaoXianjun,
I tried it but the USE_OPENCL gets ignored. Do you know why? I have opencl version 1.2.
Thanks in advance.

**Comment by JiaoXianjun** [comment]
I use this file:
LTE-Cell-Scanner / cmake / Modules / FindOPENCL.cmake 

to check if OpenCL exists.
You may check the file content to make sure cmake can find your OpenCL.
